In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
print(torch.__version__)

2.8.0+cu126


In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[0]

tensor([7, 8])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
ten = torch.tensor([[[1,2,3],
                     [4,5,6],
                     [7,8,9]]])
ten

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
ten.ndim

3

In [ ]:
ten.shape

torch.Size([1, 3, 3])

In [ ]:
ran = torch.rand(3,4)
ran

tensor([[0.4639, 0.5606, 0.7460, 0.6037],
        [0.8759, 0.3179, 0.3655, 0.5684],
        [0.7356, 0.8635, 0.6799, 0.1680]])

In [ ]:
torch.rand(3,3)

tensor([[0.0212, 0.3641, 0.2285],
        [0.3650, 0.9682, 0.0041],
        [0.2214, 0.8080, 0.8610]])

In [ ]:
torch.zeros(size=(3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
one =torch.ones(size=(3,4))
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
one.dtype

torch.float32

In [ ]:
torch.range(0,10)

/tmp/ipython-input-497691777.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
one_2_ten = torch.arange(start=1,end=11,step=1)
one_2_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zero = torch.zeros_like(input = one_2_ten)

In [ ]:
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
a+10

tensor([11, 12, 13])

In [ ]:
a*10

tensor([10, 20, 30])

In [ ]:
a-10

tensor([-9, -8, -7])

In [ ]:
a.mul(10)

tensor([10, 20, 30])

In [ ]:
a.add(10)

tensor([11, 12, 13])

In [ ]:
a.sub(1)

tensor([0, 1, 2])

In [ ]:
torch.mul(a,10)

tensor([10, 20, 30])

In [ ]:
torch.add(a,10)

tensor([11, 12, 13])

In [ ]:
torch.sub(a,1)

tensor([0, 1, 2])

matrix multi
* (3,2) @ (3,2) not work


* (3,2)@ (2,3) will work

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(3,3))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x3)

In [ ]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.1406, 0.3400],
        [0.3785, 1.2224]])

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.6344, 0.5289, 1.0487],
        [0.7714, 0.5071, 0.9773],
        [0.8328, 0.5913, 1.1511]])

In [ ]:
# tensor aggregation (max . min , sum , mean etc)

In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x)

tensor(0)

In [ ]:
x.min()

tensor(0)

In [ ]:
torch.max(x)

tensor(90)

In [ ]:
x.max()

tensor(90)

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
x.sum()

tensor(450)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

In [ ]:
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshape = x.reshape(1,9)

In [ ]:
x_reshape,x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z[:0]= 5
z , x

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshape

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshape.shape

torch.Size([1, 9])

In [ ]:
x_reshape.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])