In [1]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from 'C:\\Users\\Sahil\\anaconda3\\Lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


In [2]:
tf.__version__

'2.20.0'

In [3]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [4]:
x=tf.constant(10)
x

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [5]:
y=tf.constant(10.5)
y

<tf.Tensor: shape=(), dtype=float32, numpy=10.5>

In [6]:
z=tf.constant("India")
z

<tf.Tensor: shape=(), dtype=string, numpy=b'India'>

In [7]:
s=tf.constant([1,2,3,4,5,6])
s

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [8]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
tf.constant(a)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [9]:
t2d=tf.constant([[1,2],[3,4]])
t2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [10]:
t1d=tf.constant([[1,2,3,4]])
t1d

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[1, 2, 3, 4]], dtype=int32)>

In [11]:
t2d1=tf.constant([1,2,3,4],shape=(2,2),dtype='int32')
t2d1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [12]:
t3d1=tf.constant([[1,2],[3,4],[5,6]],shape=(2,3),dtype='float32')
t3d1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [13]:
type(t3d1)

tensorflow.python.framework.ops.EagerTensor

In [14]:
t3d1.shape

TensorShape([2, 3])

In [15]:
tf.Variable(1)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [26]:
x = tf.Variable([4, 5, 2, 9])
x.assign([1, 2, 3, 4]) 

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [27]:
x = tf.Variable([4, 5, 2, 9])
x.assign_add([4, 5, 1, 8])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 8, 10,  3, 17], dtype=int32)>

# **Tensor flow with modules**

In [ ]:
import tensorflow as tf
print(tf.version)

In [18]:
a=10
b=20

In [19]:
a+b

30

In [20]:
tf.add(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [21]:
l1=[1,2,4,45]
l2=[43,5,24,41]
tf.add(l1,l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([44,  7, 28, 86], dtype=int32)>